### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by plata** [cscarney/qreadable#1]
Do you plan to keep it as a separate library? Or shall it become part of e.g. KDE Frameworks?

**Comment by cscarney** [comment]
I'm not a KDE developer and I'm not sure exactly where it would fit into the KDE framework structure, but if I'm very much open to the idea.

**Comment by plata** [comment]
I think it would be in https://invent.kde.org/frameworks (like e.g. syndication).

The process is described in https://community.kde.org/Incubator.

**Comment by cscarney** [comment]
I don't think it quite meets the requirements for that process at this point.  I'll look into migrating development into a personal project on KDE Invent (c.f. KDE's [Application Lifecycle](https://community.kde.org/Policies/Application_Lifecycle)) and revisit the possibility of becoming an official project once it's a proper shared library with a stable API.

**Comment by cscarney** [comment]
Archiving this project and moving to https://invent.kde.org/ccarney/qreadable
